/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "midnight-void": "#0F172A",
        "on-primary-container": "#7d8497",
        "inverse-surface": "#2e3132",
        "growth-emerald": "#059669",
        "on-error-container": "#93000a",
        "inverse-primary": "#c0c6db",
        "tertiary-fixed": "#d9e3f4",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00714d",
        tertiary: "#000000",
        "surface-tint": "#575e70",
        "primary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#4edea3",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#404758",
        surface: "#f8f9fa",
        "on-tertiary-fixed-variant": "#3e4755",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        background: "#f8f9fa",
        "tertiary-fixed-dim": "#bdc7d8",
        "secondary-fixed": "#6ffbbe",
        "surface-container-low": "#f3f4f5",
        "glass-highlight": "rgba(255, 255, 255, 0.7)",
        "on-secondary-fixed-variant": "#005236",
        "surface-dim": "#d9dadb",
        "surface-border": "#E5E7EB",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-container": "#7a8594",
        "primary-fixed-dim": "#c0c6db",
        "surface-container": "#edeeef",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "secondary-container": "#6cf8bb",
        primary: "#000000",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#121c28",
        "surface-bright": "#f8f9fa",
        "on-surface-variant": "#45464c",
        outline: "#76777d",
        "tertiary-container": "#121c28",
        secondary: "#006c49",
        "primary-container": "#141b2b",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed": "#141b2b",
        "inverse-on-surface": "#f0f1f2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "16px",
        "section-gap": "80px",
        gutter: "24px",
        "margin-desktop": "40px",
        base: "8px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.03em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-sm": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.04em",
            fontWeight: "700",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.01em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
  plugins: [],
};
